# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GdTcXc5UW13hfW3fWDOQOcWMGTh-Rcy
"""

import streamlit as st
import pandas as pd
import mysql.connector
import plotly.express as px

# Page setup
st.set_page_config(layout="wide")
st.title("PhonePe Transaction Insights")

# Database connection
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Venkat@123",
    database="phonepe"
)

# Sidebar
menu = st.sidebar.selectbox("Select Analysis",
                            ["Top States", "Year Trend"])

# Top States
if menu == "Top States":
    query = """
        SELECT state, SUM(transaction_amount) AS total
        FROM aggregated_transaction
        GROUP BY state
        ORDER BY total DESC
        LIMIT 10;
    """

    df = pd.read_sql(query, conn)

    fig = px.bar(df, x="state", y="total")
    st.plotly_chart(fig)

# Year Trend
if menu == "Year Trend":
    query = """
        SELECT year, SUM(transaction_amount) AS total
        FROM aggregated_transaction
        GROUP BY year;
    """

    df = pd.read_sql(query, conn)

    fig = px.line(df, x="year", y="total")
    st.plotly_chart(fig)

conn.close()