# -*- coding: utf-8 -*-
"""etl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GdTcXc5UW13hfW3fWDOQOcWMGTh-Rcy
"""

import os
import json
import mysql.connector

# 1. Database connection
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Venkat@123",
    database="phonepe"
)

cursor = conn.cursor()

# 2. Path to data
base_path = "data/aggregated/transaction/country/india/state/"

# 3. Loop through folders
for state in os.listdir(base_path):
    state_path = os.path.join(base_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            quarter = file.replace(".json", "")
            file_path = os.path.join(year_path, file)

            with open(file_path, "r") as f:
                data = json.load(f)

            # 4. Extract values
            try:
                transactions = data["data"]["transactionData"]

                for item in transactions:
                    cursor.execute("""
                        INSERT INTO aggregated_transaction
                        (state, year, quarter, transaction_type,
                         transaction_count, transaction_amount)
                        VALUES (%s, %s, %s, %s, %s, %s)
                    """, (
                        state,
                        int(year),
                        int(quarter),
                        item["name"],
                        item["paymentInstruments"][0]["count"],
                        item["paymentInstruments"][0]["amount"]
                    ))

            except:
                continue

conn.commit()
cursor.close()
conn.close()

print("Data Loaded Successfully")

